create table public.wendao_accounts (
  user_id uuid primary key references auth.users (id) on delete cascade,
  locale text not null default 'zh'
    check (locale in ('zh', 'en')),
  memory_enabled boolean not null default true,
  weekly_reflection_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.wendao_threads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text
    check (title is null or char_length(title) between 1 and 120),
  status text not null default 'active'
    check (status in ('active', 'archived')),
  locale text not null default 'zh'
    check (locale in ('zh', 'en')),
  chapter_id integer
    check (chapter_id is null or chapter_id between 1 and 81),
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.wendao_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.wendao_threads (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null
    check (role in ('user', 'assistant')),
  content text not null
    check (char_length(content) between 1 and 12000),
  chapter_id integer
    check (chapter_id is null or chapter_id between 1 and 81),
  provider text
    check (provider is null or char_length(provider) <= 40),
  model text
    check (model is null or char_length(model) <= 80),
  request_id uuid,
  created_at timestamptz not null default now(),
  unique (user_id, request_id)
);

create table public.wendao_memories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  source_thread_id uuid references public.wendao_threads (id) on delete set null,
  kind text not null
    check (kind in (
      'current_situation',
      'recurring_theme',
      'preference_boundary',
      'practice_outcome',
      'life_manual_context'
    )),
  summary text not null
    check (char_length(summary) between 1 and 800),
  status text not null default 'active'
    check (status in ('active', 'resolved', 'expired')),
  confidence numeric(4, 3) not null default 0.500
    check (confidence between 0 and 1),
  occurred_at timestamptz,
  expires_at timestamptz,
  last_used_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.wendao_weekly_reflections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  week_start date not null,
  locale text not null default 'zh'
    check (locale in ('zh', 'en')),
  content text not null
    check (char_length(content) between 1 and 12000),
  chapter_ids integer[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, week_start)
);

create table public.wendao_entitlements (
  user_id uuid primary key references auth.users (id) on delete cascade,
  status text not null default 'none'
    check (status in ('none', 'active', 'grace', 'past_due', 'expired', 'revoked')),
  source text not null default 'none'
    check (source in ('none', 'apple', 'stripe', 'manual')),
  product_id text
    check (product_id is null or char_length(product_id) <= 120),
  provider_customer_id text
    check (provider_customer_id is null or char_length(provider_customer_id) <= 240),
  provider_subscription_id text
    check (provider_subscription_id is null or char_length(provider_subscription_id) <= 240),
  starts_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.wendao_usage_periods (
  user_id uuid not null references auth.users (id) on delete cascade,
  period_start date not null,
  period_end date not null,
  question_allowance integer not null
    check (question_allowance > 0),
  used_questions integer not null default 0
    check (used_questions between 0 and question_allowance),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, period_start),
  check (period_end > period_start)
);

create table public.wendao_billing_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  provider text not null
    check (provider in ('apple', 'stripe')),
  provider_event_id text not null
    check (char_length(provider_event_id) between 1 and 240),
  event_type text not null
    check (char_length(event_type) between 1 and 120),
  payload_hash text not null
    check (char_length(payload_hash) between 32 and 128),
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (provider, provider_event_id)
);

alter table public.wendao_profiles
  add column if not exists user_id uuid references auth.users (id) on delete set null;
alter table public.wendao_feedback
  add column if not exists user_id uuid references auth.users (id) on delete set null;
alter table public.wendao_conversations
  add column if not exists user_id uuid references auth.users (id) on delete set null;
alter table public.wendao_events
  add column if not exists user_id uuid references auth.users (id) on delete set null;

create index wendao_accounts_user_id_idx
  on public.wendao_accounts (user_id);
create index wendao_threads_user_id_idx
  on public.wendao_threads (user_id, last_message_at desc);
create index wendao_messages_user_id_idx
  on public.wendao_messages (user_id, created_at desc);
create index wendao_messages_thread_id_idx
  on public.wendao_messages (thread_id, created_at);
create index wendao_memories_user_id_idx
  on public.wendao_memories (user_id, status, updated_at desc);
create index wendao_memories_source_thread_id_idx
  on public.wendao_memories (source_thread_id);
create index wendao_weekly_reflections_user_id_idx
  on public.wendao_weekly_reflections (user_id, week_start desc);
create index wendao_entitlements_user_id_idx
  on public.wendao_entitlements (user_id);
create index wendao_usage_periods_user_id_idx
  on public.wendao_usage_periods (user_id, period_start desc);
create index wendao_billing_events_user_id_idx
  on public.wendao_billing_events (user_id, created_at desc);
create index wendao_billing_events_unprocessed_idx
  on public.wendao_billing_events (created_at)
  where processed_at is null;

create index wendao_profiles_user_id_idx
  on public.wendao_profiles (user_id)
  where user_id is not null;
create index wendao_feedback_user_id_idx
  on public.wendao_feedback (user_id, created_at desc)
  where user_id is not null;
create index wendao_conversations_user_id_idx
  on public.wendao_conversations (user_id, created_at desc)
  where user_id is not null;
create index wendao_events_user_id_idx
  on public.wendao_events (user_id, created_at desc)
  where user_id is not null;

alter table public.wendao_accounts enable row level security;
alter table public.wendao_accounts force row level security;
alter table public.wendao_threads enable row level security;
alter table public.wendao_threads force row level security;
alter table public.wendao_messages enable row level security;
alter table public.wendao_messages force row level security;
alter table public.wendao_memories enable row level security;
alter table public.wendao_memories force row level security;
alter table public.wendao_weekly_reflections enable row level security;
alter table public.wendao_weekly_reflections force row level security;
alter table public.wendao_entitlements enable row level security;
alter table public.wendao_entitlements force row level security;
alter table public.wendao_usage_periods enable row level security;
alter table public.wendao_usage_periods force row level security;
alter table public.wendao_billing_events enable row level security;
alter table public.wendao_billing_events force row level security;

revoke all on table public.wendao_accounts from anon, authenticated;
revoke all on table public.wendao_threads from anon, authenticated;
revoke all on table public.wendao_messages from anon, authenticated;
revoke all on table public.wendao_memories from anon, authenticated;
revoke all on table public.wendao_weekly_reflections from anon, authenticated;
revoke all on table public.wendao_entitlements from anon, authenticated;
revoke all on table public.wendao_usage_periods from anon, authenticated;
revoke all on table public.wendao_billing_events from anon, authenticated;

grant select on table public.wendao_accounts to authenticated;
grant select on table public.wendao_threads to authenticated;
grant select on table public.wendao_messages to authenticated;
grant select on table public.wendao_memories to authenticated;
grant select on table public.wendao_weekly_reflections to authenticated;
grant select on table public.wendao_entitlements to authenticated;
grant select on table public.wendao_usage_periods to authenticated;

create policy "Users can read their Wendao account"
on public.wendao_accounts for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their Wendao threads"
on public.wendao_threads for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their Wendao messages"
on public.wendao_messages for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their Wendao memories"
on public.wendao_memories for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their Wendao weekly reflections"
on public.wendao_weekly_reflections for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their Wendao entitlement"
on public.wendao_entitlements for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their Wendao usage"
on public.wendao_usage_periods for select
to authenticated
using ((select auth.uid()) = user_id);

create or replace function public.create_wendao_account_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.wendao_accounts (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_wendao_account_after_signup on auth.users;
create trigger create_wendao_account_after_signup
after insert on auth.users
for each row execute function public.create_wendao_account_for_new_user();

insert into public.wendao_accounts (user_id)
select id from auth.users
on conflict (user_id) do nothing;

drop trigger if exists set_wendao_account_updated_at on public.wendao_accounts;
create trigger set_wendao_account_updated_at
before update on public.wendao_accounts
for each row execute function public.set_wendao_updated_at();

drop trigger if exists set_wendao_thread_updated_at on public.wendao_threads;
create trigger set_wendao_thread_updated_at
before update on public.wendao_threads
for each row execute function public.set_wendao_updated_at();

drop trigger if exists set_wendao_memory_updated_at on public.wendao_memories;
create trigger set_wendao_memory_updated_at
before update on public.wendao_memories
for each row execute function public.set_wendao_updated_at();

drop trigger if exists set_wendao_weekly_reflection_updated_at on public.wendao_weekly_reflections;
create trigger set_wendao_weekly_reflection_updated_at
before update on public.wendao_weekly_reflections
for each row execute function public.set_wendao_updated_at();

drop trigger if exists set_wendao_entitlement_updated_at on public.wendao_entitlements;
create trigger set_wendao_entitlement_updated_at
before update on public.wendao_entitlements
for each row execute function public.set_wendao_updated_at();

drop trigger if exists set_wendao_usage_period_updated_at on public.wendao_usage_periods;
create trigger set_wendao_usage_period_updated_at
before update on public.wendao_usage_periods
for each row execute function public.set_wendao_updated_at();
