create extension if not exists pgcrypto;

create table if not exists public.wendao_profiles (
  client_id uuid primary key,
  name text
    check (name is null or char_length(name) <= 100),
  birth_date date not null,
  birth_time time not null,
  birth_place text not null
    check (char_length(birth_place) between 1 and 160),
  timezone text not null
    check (char_length(timezone) between 1 and 64),
  chart_hash text not null
    check (char_length(chart_hash) <= 96),
  chart_core jsonb not null default '{}'::jsonb,
  chart_structure jsonb not null default '{}'::jsonb,
  consent_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wendao_feedback (
  id uuid primary key default gen_random_uuid(),
  client_id uuid,
  message text not null
    check (char_length(message) between 2 and 2000),
  contact text
    check (contact is null or char_length(contact) <= 200),
  locale text not null default 'zh'
    check (locale in ('zh', 'en')),
  chapter_id integer
    check (chapter_id is null or chapter_id between 1 and 81),
  page_path text
    check (page_path is null or char_length(page_path) <= 240),
  app_version text
    check (app_version is null or char_length(app_version) <= 80),
  status text not null default 'new'
    check (status in ('new', 'reviewing', 'resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wendao_conversations (
  id uuid primary key default gen_random_uuid(),
  client_id uuid,
  session_id uuid not null,
  chapter_id integer
    check (chapter_id is null or chapter_id between 1 and 81),
  locale text not null default 'zh'
    check (locale in ('zh', 'en')),
  question text not null
    check (char_length(question) between 1 and 2000),
  answer text not null
    check (char_length(answer) between 1 and 6000),
  chart_hash text
    check (chart_hash is null or char_length(chart_hash) <= 96),
  created_at timestamptz not null default now()
);

create table if not exists public.wendao_events (
  id bigint generated by default as identity primary key,
  client_id uuid,
  session_id uuid not null,
  event_name text not null
    check (event_name in (
      'app_open',
      'chapter_view',
      'directory_open',
      'chance_chapter',
      'language_change',
      'theme_change',
      'composer_focus',
      'question_submit',
      'profile_open',
      'profile_saved',
      'chart_calculated',
      'feedback_submit',
      'contact_click'
    )),
  chapter_id integer
    check (chapter_id is null or chapter_id between 1 and 81),
  locale text not null default 'zh'
    check (locale in ('zh', 'en')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists wendao_feedback_created_at_idx
  on public.wendao_feedback (created_at desc);
create index if not exists wendao_conversations_created_at_idx
  on public.wendao_conversations (created_at desc);
create index if not exists wendao_events_created_at_idx
  on public.wendao_events (created_at desc);
create index if not exists wendao_events_name_idx
  on public.wendao_events (event_name, created_at desc);
create index if not exists wendao_events_client_idx
  on public.wendao_events (client_id, created_at desc);

alter table public.wendao_profiles enable row level security;
alter table public.wendao_feedback enable row level security;
alter table public.wendao_conversations enable row level security;
alter table public.wendao_events enable row level security;

revoke all on table public.wendao_profiles from anon, authenticated;
revoke all on table public.wendao_feedback from anon, authenticated;
revoke all on table public.wendao_conversations from anon, authenticated;
revoke all on table public.wendao_events from anon, authenticated;

create or replace function public.set_wendao_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_wendao_profile_updated_at on public.wendao_profiles;
create trigger set_wendao_profile_updated_at
before update on public.wendao_profiles
for each row execute function public.set_wendao_updated_at();

drop trigger if exists set_wendao_feedback_updated_at on public.wendao_feedback;
create trigger set_wendao_feedback_updated_at
before update on public.wendao_feedback
for each row execute function public.set_wendao_updated_at();
